import { Product } from "@/types/types";
export const Trending: Product[] = [
  {
    id: "22",
    name: "Smart Fitness Watch",
    price: 149.99,
    rating: 4.5,
    reviewCount: 215,
    images: ["/images/smartwatch.webp"],
    description:
      "Waterproof fitness tracker with heart rate monitor, sleep tracking, and 7-day battery life. Compatible with iOS and Android. Tracks 15+ workout modes.",
    category: "Electronics",
    stock: 35,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "10",
    name: "Athletic Jogger Pants",
    price: 34.99,
    discountPrice: 29.99,
    rating: 4.4,
    reviewCount: 134,
    images: ["/images/fitpant.webp"],
    description:
      "Performance joggers made from lightweight, moisture-wicking fabric with 4-way stretch. Elastic waistband with adjustable drawstring and zippered security pocket. Tapered leg with ribbed cuffs. Reflective details for nighttime visibility. Perfect for workouts or casual wear.",
    category: "Clothing",
    stock: 50,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "17",
    name: "Electric Facial Cleanser",
    price: 59.99,
    rating: 4.5,
    reviewCount: 210,
    images: ["/images/Electric-Facial-Cleanser.jpg"],
    description:
      "Sonic facial cleansing brush with 6 interchangeable heads for different skin needs. Waterproof design for shower use. 3-speed settings from gentle to deep clean. Rechargeable battery lasts 30 days per charge. Includes travel case and acne-clearing brush head. Clinically proven to remove 99.5% of makeup and impurities.",
    category: "Beauty",
    stock: 30,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "25",
    name: "Smart Air Fryer",
    price: 119.99,
    rating: 4.6,
    reviewCount: 587,
    images: ["/images/Smart-Air-Fryer.jpg"],
    description:
      "5.8-quart digital air fryer with 7 cooking presets and 400°F max temperature. 1500W power with rapid air circulation technology. Dishwasher-safe parts.",
    category: "Home & Kitchen",
    stock: 17,
    isFavorited: false,
    addedToCard: false,
  },
];
export const featuredProducts: Product[] = [
  {
    id: "18",
    name: "Yoga Mat",
    price: 29.99,
    rating: 4.7,
    reviewCount: 345,
    images: ["/images/Yoga-Mat.jpeg"],
    description:
      'Premium non-slip yoga mat made from eco-friendly TPE material. Extra thick 6mm cushioning provides joint support during workouts. Includes carrying strap and features alignment markers for perfect poses. Measures 72" long x 24" wide.',
    category: "Sports",
    stock: 40,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "31",
    name: "Foldable Bluetooth Keyboard",
    price: 59.99,
    rating: 4.4,
    reviewCount: 128,
    images: ["/images/Foldable-Bluetooth-Keyboard.webp"],
    description:
      "Ultra-thin foldable Bluetooth keyboard compatible with all devices. Water-resistant design with 6-month battery life. Perfect for travel with its compact folded size.",
    category: "Electronics",
    stock: 35,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "32",
    name: "Cashmere Sweater",
    price: 129.99,
    rating: 4.8,
    reviewCount: 215,
    images: ["/images/Cashmere-Sweater.jpeg"],
    description:
      "100% pure cashmere crewneck sweater with ribbed trim. Luxuriously soft and lightweight yet warm. Available in classic neutral tones. Dry clean only.",
    category: "Clothing",
    stock: 22,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "34",
    name: "LED Light Therapy Mask",
    price: 89.99,
    rating: 4.6,
    reviewCount: 187,
    images: ["/images/LED-Light-Therapy-Mask.jpg"],
    description:
      "Professional-grade LED light therapy mask with 7 color settings for different skin concerns. Rechargeable battery with 30 treatments per charge. Includes protective goggles.",
    category: "Beauty",
    stock: 25,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "35",
    name: "Resistance Band Set",
    price: 39.99,
    rating: 4.5,
    reviewCount: 276,
    images: ["/images/Resistance-Band-Set.jpeg"],
    description:
      "5-piece latex resistance band set with varying tension levels. Includes door anchor, ankle straps, and carrying case. Ideal for full-body workouts anywhere.",
    category: "Sports",
    stock: 40,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "33",
    name: "Smart Coffee Maker",
    price: 149.99,
    rating: 4.7,
    reviewCount: 342,
    images: ["/images/Smart-Coffee-Maker.jpeg"],
    description:
      "WiFi-enabled coffee maker with app control and voice command compatibility. 12-cup capacity with programmable brewing. Includes permanent gold-tone filter.",
    category: "Home & Kitchen",
    stock: 18,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "3",
    name: "4K Ultra HD Smart TV",
    price: 899.99,
    rating: 4.8,
    reviewCount: 320,
    images: ["/images/smartTv.jpg"],
    description:
      "55-inch 4K HDR10+ smart TV with quantum dot technology for breathtaking color accuracy. Built-in voice control with Alexa compatibility. Includes all major streaming apps pre-installed. 120Hz refresh rate eliminates motion blur for sports and action movies.",
    category: "Electronics",
    stock: 15,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "11",
    name: "Air Fryer 5.8QT",
    price: 119.99,
    rating: 4.7,
    reviewCount: 278,
    images: ["/images/airFryer.webp"],
    description:
      "Large capacity air fryer with 7 one-touch cooking presets including roast, bake, and dehydrate. Digital touchscreen with adjustable temperature (180-400°F) and 60-minute timer. Non-stick basket is dishwasher safe for easy cleaning. Cooks with 75% less fat than traditional frying.",
    category: "Home & Kitchen",
    stock: 20,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "7",
    name: "Men's Slim Fit Jeans",
    price: 49.99,
    discountPrice: 39.99,
    rating: 4.3,
    reviewCount: 156,
    images: ["/images/jeans.jpeg"],
    description:
      'Modern slim fit jeans made with premium stretch denim for all-day comfort. Classic medium blue wash with subtle fading details. Reinforced stitching at stress points. Mid-rise waist with 32" inseam (other lengths available). Machine wash cold, tumble dry low.',
    category: "Clothing",
    stock: 60,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "15",
    name: "Vitamin C Serum",
    price: 24.99,
    discountPrice: 19.99,
    rating: 4.6,
    reviewCount: 432,
    images: ["/images/viteminC.webp"],
    description:
      "Potent 20% vitamin C serum with hyaluronic acid and vitamin E. Brightens dull skin, reduces appearance of dark spots and fine lines. Lightweight, fast-absorbing formula suitable for all skin types. Dermatologist tested, cruelty-free, and packaged in UV-protective bottle to maintain potency.",
    category: "Beauty",
    stock: 90,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "6",
    name: "Noise-Cancelling Headphones",
    price: 199.99,
    discountPrice: 179.99,
    rating: 4.9,
    reviewCount: 420,
    images: ["/images/headphones.webp"],
    description:
      "Premium over-ear headphones with advanced active noise cancellation technology. 40-hour battery life with quick charge (5 mins = 4 hrs playback). Crystal clear calls with built-in microphone. Plush memory foam ear cushions for extended comfort. Includes carrying case and airline adapter.",
    category: "Electronics",
    stock: 25,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "12",
    name: "Stainless Steel Cookware Set",
    price: 249.99,
    discountPrice: 199.99,
    rating: 4.8,
    reviewCount: 145,
    images: ["/images/stanlesSteal.webp"],
    description:
      'Professional 10-piece stainless steel cookware set with impact-bonded aluminum bases for even heat distribution. Oven safe to 500°F. Includes 8" and 10" fry pans, 1.5qt and 3qt saucepans with lids, and 5qt stockpot. Induction compatible and dishwasher safe for easy cleanup.',
    category: "Home & Kitchen",
    stock: 12,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "20",
    name: "Running Shoes",
    price: 119.99,
    discountPrice: 99.99,
    rating: 4.9,
    reviewCount: 520,
    images: ["/images/runningShose.jpg"],
    description:
      "Performance running shoes with responsive cushioning for high-energy rebound. Breathable mesh upper with reinforced toe cap. Rubber outsole provides excellent traction on both roads and trails. Removable cushioned insole accommodates orthotics. Available in multiple width options.",
    category: "Sports",
    stock: 25,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "1",
    name: "Wireless Bluetooth Earbuds",
    price: 89.99,
    discountPrice: 69.99,
    rating: 4.5,
    reviewCount: 245,
    images: ["/images/wirelessheadphone1.jpeg"],
    description:
      "True wireless earbuds with Bluetooth 5.2 for stable connection up to 30 feet. 20-hour total battery life (5hrs per charge + 3 charges from case). IPX5 water resistance withstands sweat and rain. Touch controls for music, calls, and voice assistant. Comes with 3 sizes of silicone ear tips for custom fit.",
    category: "Electronics",
    stock: 50,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "9",
    name: "Unisex Cotton T-Shirt",
    price: 19.99,
    rating: 4.0,
    reviewCount: 89,
    images: ["/images/Tshirt.webp"],
    description:
      "Classic crewneck t-shirt made from 100% premium combed cotton for superior softness. Reinforced shoulder-to-shoulder tape for durability. Available in 12 colors from neutrals to bold hues. Pre-shrunk fabric maintains shape wash after wash. Unisex sizing from XS to XXL.",
    category: "Clothing",
    stock: 100,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "16",
    name: "Matte Lipstick Set",
    price: 29.99,
    rating: 4.3,
    reviewCount: 178,
    images: ["/images/lipsteakSet.jpeg"],
    description:
      "Luxury matte lipstick set featuring 6 highly pigmented shades from everyday nudes to statement reds. Long-wearing formula glides on smoothly without drying lips. Enriched with vitamin E and avocado oil for comfortable wear. Paraben-free and cruelty-free. Includes mini sharpener for precise application.",
    category: "Beauty",
    stock: 55,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "4",
    name: "Gaming Laptop",
    price: 1299.99,
    rating: 4.6,
    reviewCount: 112,
    images: ["/images/gamingLaptop.jpg"],
    description:
      'High-performance gaming laptop with NVIDIA RTX 3060 GPU and 11th Gen Intel Core i7 processor. 15.6" 144Hz IPS display with 100% sRGB coverage. 16GB DDR4 RAM and 1TB NVMe SSD provide lightning-fast load times. RGB backlit keyboard with anti-ghosting technology. Dual fan cooling system maintains optimal temperatures during marathon sessions.',
    category: "Electronics",
    stock: 10,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "14",
    name: "Memory Foam Pillow",
    price: 39.99,
    rating: 4.4,
    reviewCount: 320,
    images: ["/images/pellow.webp"],
    description:
      "Contour memory foam pillow designed by chiropractors to align spine and relieve neck pain. Hypoallergenic shredded foam adapts to your sleeping position. Removable bamboo cover is breathable and machine washable. Medium firmness suitable for back and side sleepers. Includes bonus travel bag.",
    category: "Home & Kitchen",
    stock: 65,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "19",
    name: "Dumbbell Set (10kg)",
    price: 79.99,
    rating: 4.8,
    reviewCount: 112,
    images: ["/images/dumbleset.webp"],
    description:
      "Adjustable dumbbell set with 10kg total weight (5kg per dumbbell). Textured rubber coating provides secure grip and protects floors. 8 weight plates (4x1.25kg, 4x0.5kg) allow for 2.5kg increments. Chrome-plated steel handles with secure locking collars. Ideal for home workouts and strength training.",
    category: "Sports",
    stock: 15,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "8",
    name: "Women's Oversized Hoodie",
    price: 44.99,
    rating: 4.5,
    reviewCount: 210,
    images: ["/images/oversizeHoddi.webp"],
    description:
      "Cozy oversized hoodie made from premium fleece with a soft brushed interior. Relaxed fit with dropped shoulders and kangaroo pocket. Ribbed cuffs and hem for better fit. Available in 8 neutral and pastel colors. Machine washable without pilling or fading.",
    category: "Clothing",
    stock: 45,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "13",
    name: "Robot Vacuum Cleaner",
    price: 299.99,
    rating: 4.6,
    reviewCount: 187,
    images: ["/images/robotvacumeCleaner.jpeg"],
    description:
      "Smart robot vacuum with laser navigation for precise room mapping. Powerful suction picks up pet hair and debris. Connects to WiFi for app control and scheduling. Self-charging and can clean for up to 150 minutes per charge. Includes HEPA filter to trap 99.97% of allergens. Works with Alexa and Google Assistant.",
    category: "Home & Kitchen",
    stock: 8,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "2",
    name: "Smartphone 128GB",
    price: 699.99,
    discountPrice: 649.99,
    rating: 4.7,
    reviewCount: 189,
    images: ["/images/smarPhone.jpeg"],
    description:
      'Flagship smartphone with 6.5" AMOLED display featuring 120Hz refresh rate. Triple camera system includes 64MP main sensor, ultra-wide, and macro lenses. 128GB storage with 8GB RAM for smooth multitasking. 5000mAh battery lasts all day with fast charging support. 5G capable with in-display fingerprint sensor.',
    category: "Electronics",
    stock: 30,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "21",
    name: "Wireless Noise-Canceling Headphones",
    price: 199.99,
    rating: 4.7,
    reviewCount: 342,
    images: ["/images/wirelessHeadphones.webp"],
    description:
      "Premium over-ear headphones with active noise cancellation, 30-hour battery life, and crystal-clear Bluetooth 5.0 audio. Includes carrying case and 3.5mm audio cable.",
    category: "Electronics",
    stock: 28,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "22",
    name: "Smart Fitness Watch",
    price: 149.99,
    rating: 4.5,
    reviewCount: 215,
    images: ["/images/smartwatch.webp"],
    description:
      "Waterproof fitness tracker with heart rate monitor, sleep tracking, and 7-day battery life. Compatible with iOS and Android. Tracks 15+ workout modes.",
    category: "Electronics",
    stock: 35,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "10",
    name: "Athletic Jogger Pants",
    price: 34.99,
    discountPrice: 29.99,
    rating: 4.4,
    reviewCount: 134,
    images: ["/images/fitpant.webp"],
    description:
      "Performance joggers made from lightweight, moisture-wicking fabric with 4-way stretch. Elastic waistband with adjustable drawstring and zippered security pocket. Tapered leg with ribbed cuffs. Reflective details for nighttime visibility. Perfect for workouts or casual wear.",
    category: "Clothing",
    stock: 50,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "17",
    name: "Electric Facial Cleanser",
    price: 59.99,
    rating: 4.5,
    reviewCount: 210,
    images: ["/images/Electric-Facial-Cleanser.jpg"],
    description:
      "Sonic facial cleansing brush with 6 interchangeable heads for different skin needs. Waterproof design for shower use. 3-speed settings from gentle to deep clean. Rechargeable battery lasts 30 days per charge. Includes travel case and acne-clearing brush head. Clinically proven to remove 99.5% of makeup and impurities.",
    category: "Beauty",
    stock: 30,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "25",
    name: "Smart Air Fryer",
    price: 119.99,
    rating: 4.6,
    reviewCount: 587,
    images: ["/images/Smart-Air-Fryer.jpg"],
    description:
      "5.8-quart digital air fryer with 7 cooking presets and 400°F max temperature. 1500W power with rapid air circulation technology. Dishwasher-safe parts.",
    category: "Home & Kitchen",
    stock: 17,
    isFavorited: false,
    addedToCard: false,
  },

  {
    id: "27",
    name: "Ceramic Hair Straightener",
    price: 89.99,
    rating: 4.5,
    reviewCount: 327,
    images: ["/images/Hair-Straightener.webp"],
    description:
      "1-inch ceramic tourmaline flat iron with adjustable temperature up to 450°F. 30-second heat up and auto shut-off for safety.",
    category: "Beauty",
    stock: 21,
    addedToCard: false,
    isFavorited: false,
  },
  {
    id: "29",
    name: "Adjustable Kettlebell (5-20kg)",
    price: 129.99,
    rating: 4.6,
    reviewCount: 287,
    images: ["/images/Adjustable-Kettlebell.webp"],
    description:
      "Space-saving adjustable kettlebell with 5 weight settings (5kg, 10kg, 15kg, 18kg, 20kg). Durable cast iron construction with ergonomic handle.",
    category: "Sports",
    stock: 14,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "30",
    name: "Running Shoes",
    price: 99.99,
    rating: 4.7,
    reviewCount: 843,
    images: ["/images/runningShose1.webp"],
    description:
      "Lightweight running shoes with responsive cushioning. Breathable mesh upper with reinforced toe cap. Non-marking rubber outsole with traction pattern.",
    category: "Sports",
    stock: 27,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "28",
    name: "Hydrating Face Mask (5-pack)",
    price: 19.99,
    rating: 4.7,
    reviewCount: 512,
    images: ["/images/faceMask.jpeg"],
    description:
      "Sheet masks infused with hyaluronic acid and aloe vera. Dermatologist tested. Paraben-free and cruelty-free. Suitable for sensitive skin.",
    category: "Beauty",
    stock: 78,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "23",
    name: "Slim Fit Jeans",
    price: 59.99,
    rating: 4.2,
    reviewCount: 203,
    images: ["/images/mens-jeans.jpg"],
    description:
      "Stretch denim jeans with modern slim fit. Abrasion-resistant fabric with reinforced knees. Mid-rise waist with five-pocket styling.",
    category: "Clothing",
    stock: 32,
    isFavorited: false,
    addedToCard: false,
  },
  {
    id: "24",
    name: "Lightweight Hooded Jacket",
    price: 89.99,
    rating: 4.5,
    reviewCount: 97,
    images: ["/images/jacket.webp"],
    description:
      "Water-resistant windbreaker with adjustable hood and zippered pockets. Breathable mesh lining. Packs into its own pocket for travel.",
    category: "Clothing",
    stock: 18,
    addedToCard: false,
    isFavorited: false,
  },
  {
    id: "5",
    name: "Wireless Charging Pad",
    price: 29.99,
    rating: 4.2,
    reviewCount: 95,
    images: ["/images/Wireless-Charging-Pad.webp"],
    description:
      "Fast Qi-certified wireless charging pad delivers up to 15W power for compatible devices. Non-slip silicone surface keeps phone in place. LED indicator shows charging status. Compact design with 6ft braided nylon cable. Built-in safeguards prevent overheating and overcharging.",
    category: "Electronics",
    stock: 80,
    isFavorited: false,
    addedToCard: false,
  },
];

export const fakeReviews = [
  {
    id: "1",
    userName: "Alex Johnson",
    rating: 5,
    comment:
      "Absolutely love this product! It exceeded all my expectations and works perfectly.",
    date: "2023-10-15",
    helpful: 24,
    verified: true,
    hasVoted: false,
  },
  {
    id: "2",
    userName: "Sam Wilson",
    rating: 4,
    comment:
      "Great quality for the price. Only giving 4 stars because the color was slightly different than expected.",
    date: "2023-09-28",
    helpful: 12,
    verified: false,
    hasVoted: false,
  },
  {
    id: "3",
    userName: "Taylor Smith",
    rating: 3,
    comment:
      "It's okay, but not as durable as I hoped. Broke after a few months of regular use.",
    date: "2023-08-10",
    helpful: 5,
    verified: true,
    hasVoted: false,
  },
];
